// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibhcbkmepfxjqxoowour.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaGNia21lcGZ4anF4b293b3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODAxMTksImV4cCI6MjA1OTM1NjExOX0.gnK3IaEuzU1kq1uMWjx-7o6pak5_xO95IyJv_QMrgK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);